#!/usr/bin/env bash
# Assembles a linux-denys Arch Linux package from pre-built kernel artifacts.
# Does NOT recompile — expects the build outputs already present.
#
# Usage:
#   make-pkg.sh <artifacts-dir> <output-dir>
#
#   artifacts-dir must contain:
#     Image.gz                        - compressed kernel image
#     sc8180x-surface-pro-x.dtb      - device tree blob
#     modules.tar.gz                  - kernel modules (layout: lib/modules/<kernver>/...)
#
# Requirements: tar, zstd, fakeroot (all available via pacman or conda)

set -euo pipefail

ARTIFACTS_DIR="$(realpath "$1")"
OUTPUT_DIR="$(realpath "$2")"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

PKGBASE="linux-denys"
PKGVER="${PKGVER:-$(make -s -C "$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)" kernelversion | tr '-' '_')}"
PKGREL="${PKGREL:-1}"
ARCH="aarch64"
BUILDDATE="$(date +%s)"
PACKAGER="${PACKAGER:-CI <ci@github>}"

# Derive the kernel release string from the modules directory name
# (e.g. 6.18.3-1-denys)
KERNVER="$(set +o pipefail; tar -tzf "${ARTIFACTS_DIR}/modules.tar.gz" \
    | grep -m1 'lib/modules/[^/]*/modules.builtin' \
    | sed 's|.*lib/modules/||;s|/modules.builtin||')"

if [[ -z "$KERNVER" ]]; then
    echo "ERROR: could not determine kernel version from modules.tar.gz" >&2
    exit 1
fi

echo "==> Packaging ${PKGBASE} ${PKGVER}-${PKGREL} (kernver: ${KERNVER})"

# ── Build the staging tree ───────────────────────────────────────────────────

STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT

MODULESDIR="${STAGING}/usr/lib/modules/${KERNVER}"

# Kernel image + pkgbase marker
install -Dm644 "${ARTIFACTS_DIR}/Image.gz" "${MODULESDIR}/vmlinuz"
printf '%s' "${PKGBASE}" | install -Dm644 /dev/stdin "${MODULESDIR}/pkgbase"

# Modules (the tarball is already rooted at the filesystem root)
tar -xzf "${ARTIFACTS_DIR}/modules.tar.gz" -C "${STAGING}"

# Remove the build symlink (belongs in -headers, not here)
rm -f "${MODULESDIR}/build"

# DTBs
install -Dm644 \
    "${ARTIFACTS_DIR}/sc8180x-surface-pro-x.dtb" \
    "${MODULESDIR}/dtb/qcom/sc8180x-surface-pro-x.dtb"
mkdir -p "${STAGING}/boot/dtb"
cp -r "${MODULESDIR}/dtb" "${STAGING}/boot/dtb/${PKGBASE}"

# mkinitcpio preset
PRESET_DEST="${STAGING}/etc/mkinitcpio.d/${PKGBASE}.preset"
sed \
    -e "s|%PKGBASE%|${PKGBASE}|g" \
    -e "s|%KERNVER%|${KERNVER}|g" \
    "${SCRIPT_DIR}/linux-denys.preset" \
    | install -Dm644 /dev/stdin "${PRESET_DEST}"

# ── Compute installed size (in KiB, rounded up) ──────────────────────────────

INSTALLED_SIZE=$(du -sk "${STAGING}" | cut -f1)

# ── Write .PKGINFO ───────────────────────────────────────────────────────────

cat > "${STAGING}/.PKGINFO" <<EOF
# Generated by make-pkg.sh
pkgname = ${PKGBASE}
pkgbase = ${PKGBASE}
xdata = pkgtype=pkg
pkgver = ${PKGVER}-${PKGREL}
pkgdesc = Linux Surface Pro X kernel and modules
url = https://github.com/denysvitali/linux-surface
builddate = ${BUILDDATE}
packager = ${PACKAGER}
size = $((INSTALLED_SIZE * 1024))
arch = ${ARCH}
license = GPL-2.0-only
depend = coreutils
depend = linux-firmware
depend = kmod
depend = mkinitcpio>=0.7
optdepend = crda: to set the correct wireless channels of your country
EOF

# ── Write .INSTALL ────────────────────────────────────────────────────────────

cp "${SCRIPT_DIR}/linux-denys.install" "${STAGING}/.INSTALL"

# ── Pack ─────────────────────────────────────────────────────────────────────

mkdir -p "${OUTPUT_DIR}"
PKG_FILE="${OUTPUT_DIR}/${PKGBASE}-${PKGVER}-${PKGREL}-${ARCH}.pkg.tar.zst"

echo "==> Disk usage before packaging:"
df -h / /home/runner 2>/dev/null || df -h /
echo "==> Staging tree size: $(du -sh "${STAGING}" 2>/dev/null)"

echo "==> Creating ${PKG_FILE}"
# fakeroot is preferred (sets uid/gid to 0:0 in the archive) but not strictly
# required for a functional package — fall back gracefully if unavailable.
FAKEROOT=""
if command -v fakeroot &>/dev/null; then
    FAKEROOT="fakeroot --"
else
    echo "  [warn] fakeroot not found; archive will use current uid/gid"
fi

# Disable pipefail: tar receives SIGPIPE (exit 2) when zstd closes the pipe
# after consuming all input. This is normal and not an error.
(set +o pipefail; $FAKEROOT tar \
    --numeric-owner \
    -C "${STAGING}" \
    -cf - \
    . \
    | zstd -T0 -o "${PKG_FILE}")
TAR_STATUS=$?

if [ $TAR_STATUS -ne 0 ] && [ $TAR_STATUS -ne 2 ]; then
    echo "ERROR: tar exited with status ${TAR_STATUS}" >&2
    exit 1
fi

# Verify the archive is valid and non-empty
if [ ! -s "${PKG_FILE}" ]; then
    echo "ERROR: package file is empty or was not created" >&2
    exit 1
fi

echo "==> Done: ${PKG_FILE}"
