options soundwire_qcom spx_core_enum=1 spx_force_attach=1 spx_blind_attach=1 spx_frame_phase=1 spx_runtime_ssp_period=1 spx_actual_phase=0 spx_clk_div=0
options snd_soc_wsa881x spx_powerdown_gpio=1 spx_stream_port_mask=3 spx_sample_edge=12
