options wcd934x spx_wsa_en_pin=2
options snd_soc_wcd934x spx_clear_npl=1
options q6adm spx_v7_flags=16384 spx_v7_endpoint=-1
options q6routing spx_rx_topology=0 spx_rx_app_type=0 spx_rx_acdb_id=0
options q6asm_dai alias_prot=3
